<?php

// autoload.php @generated by Composer

require_once 'C:\Users\Sabal\Desktop\Mapache\Mapache\vendor\composer\autoload_real.php';

return ComposerAutoloaderInit92225555e9583ea906f075a85ed763d6::getLoader();
